<a href="https://colab.research.google.com/github/PriscillaAlmeida07/ifood-data-science/blob/main/notebooks/ifood_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Food Delivery Times Analysis

In [44]:
# Dependencies
# This project uses the following libraries:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading the dataset and checking some key information to get a clear overview for our analysis.

In [52]:
df = pd.read_csv('Food_Delivery_Times.csv', sep=',')

# Display a concise summary of the DataFrame, including data types and non-null values.
print('------------------ Overview ------------------\n')
df.info()

# Calculate and display the count of missing values for each column.
print('\n------------------ Missing values ------------------\n')
print(df.isna().sum())

# Display the first 20 rows of the DataFrame to get a preliminary look at the data.
print('\n------------------ 20 rows ------------------\n')
df.head(20)

------------------ Overview ------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

------------------ Missing values ------------------

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

------------------ 5 rows ------------------

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68
5,679,19.40,Clear,Low,Evening,Scooter,8,9.0,57
6,627,9.52,Clear,Low,NaN,Bike,12,1.0,49
7,514,17.39,Clear,Medium,Evening,Scooter,5,6.0,46
8,860,1.78,Snowy,Low,Evening,Car,20,6.0,35
9,137,10.62,Foggy,Low,Evening,Scooter,29,1.0,73
10,812,16.86,Snowy,Medium,Afternoon,Car,13,4.0,88
11,77,15.54,Clear,Low,Night,Bike,29,1.0,76
12,637,10.89,Clear,High,Night,Bike,12,5.0,53
13,974,4.69,Rainy,Medium,Evening,Scooter,12,7.0,36
14,939,2.80,Clear,High,Morning,Scooter,10,NaN,33
15,900,2.17,Snowy,Low,Evening,Car,15,3.0,35
16,281,17.86,Rainy,Low,Afternoon,Bike,5,1.0,50
17,884,2.53,Snowy,Low,Morning,Bike,6,8.0,24
18,762,6.58,Foggy,Low,Evening,Car,6,7.0,27
19,320,5.38,Clear,Medium,Evening,Scooter,26,1.0,47

### Handle missing data.

In [53]:
# This treats missing values as a distinct category for categorical columns and a placeholder for numerical columns.
df = df.fillna('NA')
# Display the first 10 rows of the DataFrame to verify the missing value imputation.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 1000 non-null   object
 3   Traffic_Level           1000 non-null   object
 4   Time_of_Day             1000 non-null   object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  1000 non-null   object
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(1), int64(3), object(5)
memory usage: 70.4+ KB

### Checking duplicate rows

In [47]:
# Check for duplicate rows in the DataFrame.
df.duplicated().sum()
# Conclusion: The output of 0 confirms that there are no duplicate entries in the dataset.

np.int64(0)

# Data Analysis

### 1 - Correlation

In [54]:
# Calculate the Pearson correlation coefficient between 'Distance_km' and 'Delivery_Time_min'.
correlation = df['Distance_km'].corr(df['Delivery_Time_min'])
print(f'Correlation between Distance_km and Delivery_Time_min:', correlation)
# Compute correlations for all numerical columns with 'Delivery_Time_min' and sort them in descending order.
df.corr(numeric_only=True)['Delivery_Time_min'].sort_values(ascending=False)

# Conclusion: 'Distance_km' exhibits the strongest positive correlation with 'Delivery_Time_min'.
# This implies that as the delivery distance increases, the delivery time tends to increase proportionally.

Correlation between Distance_km and Delivery_Time_min: 0.7809983586157747

Delivery_Time_min       1.000000
Distance_km             0.780998
Preparation_Time_min    0.307350
Order_ID               -0.036650
Name: Delivery_Time_min, dtype: float64

### 2 -

In [51]:
# Analyze the influence of categorical variables on 'Delivery_Time_min' by calculating the mean delivery time for each category.
# Group by 'Weather' and calculate the mean 'Delivery_Time_min', sorted in descending order.
df.groupby('Weather')['Delivery_Time_min'].mean().sort_values(ascending=False)
# Group by 'Traffic_Level' and calculate the mean 'Delivery_Time_min', sorted in descending order.
df.groupby('Traffic_Level')['Delivery_Time_min'].mean().sort_values(ascending=False)
# Group by 'Vehicle_Type' and calculate the mean 'Delivery_Time_min', sorted in descending order.
df.groupby('Vehicle_Type')['Delivery_Time_min'].mean().sort_values(ascending=False)
# Group by 'Time_of_Day' and calculate the mean 'Delivery_Time_min', sorted in descending order.
df.groupby('Time_of_Day')['Delivery_Time_min'].mean().sort_values(ascending=False)

Time_of_Day
NA           66.166667
Evening      57.481229
Morning      56.120130
Afternoon    56.080986
Night        55.211765
Name: Delivery_Time_min, dtype: float64

### View